=== compozerr/base/compozerr.schema.json
{
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "project",
        "module"
      ]
    },
    "name": {
      "type": "string"
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "start": {
      "type": "string"
    },
    "startupTimeoutMs": {
      "type": "number"
    },
    "readyMessage": {
      "type": "string"
    },
    "end": {
      "type": "string"
    },
    "port": {
      "type": "string"
    },
    "backend": {
      "type": "object",
      "properties": {
        "defaultEnvProperties": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "frontend": {
      "type": "object",
      "properties": {
        "srcDir": {
          "type": "string",
          "default": "frontend/src"
        },
        "routesDir": {
          "type": "string"
        },
        "routePrefix": {
          "type": "string"
        },
        "defaultEnvProperties": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "default": {
        "alias": "@/*",
        "srcDir": "frontend/src"
      }
    },
    "dockerComposeFile": {
      "type": "string"
    }
  },
  "required": [
    "type",
    "name"
  ],
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== compozerr/base/modules/openTelemetry/compozerr.json
{
    "type": "module",
    "name": "openTelemetry",
    "start": "docker-compose up",
    "dockerComposeFile": "docker-compose.yml",
    "end": "docker-compose down",
    "readyMessage": "Now listening on: http://[::]",
    "backend": {
        "defaultEnvProperties": {
            "OTEL_EXPORTER_OTLP_ENDPOINT": "http://openTelemetry:18889"
        }
    }
}

=== compozerr/base/modules/stripe/compozerr.json
{
    "type": "module",
    "name": "stripe",
    "dependencies": {
        "compozerr-lib/auth": "*"
    },
    "end": "",
    "port": "",
    "frontend": {
        "routesDir": "frontend/src/routes"
    },
    "backend": {
        "defaultEnvProperties": {
            "STRIPE__API_KEY": "<YOUR_STRIPE_API_KEY>"
        }
    }
}
